---
# tasks file for apache
- name: Install apache httpd
  yum:
    name: "{{rpm}}"
    state: installed
- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/
    owner: apache
    group: apache
    mode: 0755
  notify:
    - Restart services
- name: Start services
  service:
    name: "{{rpm}}"
    state: started
    enabled: true
